<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My E-commerce Store</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <!-- Header -->
    <header>
        <nav>
            <ul>
                <li><a href="index.html">Home</a></li>
                <li><a href="products.html">Products</a></li>
                <li><a href="cart.html">Cart</a></li>
            </ul>
        </nav>
    </header>

    <!-- Main Content -->
    <main>
        <section class="hero">
            <h1>Welcome to My E-commerce Store</h1>
            <p>Your favorite products, now at your fingertips.</p>
            <a href="products.html" class="btn">Shop Now</a>
        </section>

        <section class="featured-products">
            <h2>Featured Products</h2>
            <div class="product-card">
                <img src="https://via.placeholder.com/150" alt="Product 1">
                <h3>Product 1</h3>
                <p>$19.99</p>
                <button class="add-to-cart" data-product="1">Add to Cart</button>
            </div>
            <div class="product-card">
                <img src="https://via.placeholder.com/150" alt="Product 2">
                <h3>Product 2</h3>
                <p>$29.99</p>
                <button class="add-to-cart" data-product="2">Add to Cart</button>
            </div>
            <!-- Add more products as needed -->
        </section>
    </main>

    <!-- Footer -->
    <footer>
        <p>&copy; 2025 My E-commerce Store</p>
    </footer>

    <script src="script.js"></script>
</body>
</html>
